version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: movie_mate
      MYSQL_USER: movie_mate_user
      MYSQL_PASSWORD: movie_mate_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
