spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/movie_mate
    username: movie_mate_user
    password: movie_mate_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: MY_SUPER_STRONG_JWT_SECRET!123

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      moviemate: DEBUG