spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:./config/.env.properties
  datasource:
    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: ci
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

jwt:
  secret: MY_SUPER_STRONG_JWT_SECRET!123

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      moviemate: DEBUG