spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:./config/.env.properties
  datasource:
    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
---
spring:
  config:
    activate:
      on-profile: no-db
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      moviemate: DEBUG