spring:
  config:
    import: optional:file:./config/.env.properties
  datasource:
    url: jdbc:mysql://localhost:3307/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: MY_SUPER_STRONG_JWT_SECRET!123

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      moviemate: DEBUG