spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:./config/.env.properties
  datasource:
    url: jdbc:mysql://localhost:3307/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: ci
  datasource:
    url: jdbc:mysql://mysql:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: MY_SUPER_STRONG_JWT_SECRET!123

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      moviemate: DEBUG