name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-17
      env:
        SPRING_PROFILES_ACTIVE: prod
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install MySQL Client
        run: |
          apt-get update && apt-get install -y mysql-client
        shell: bash

      - name: Wait for MySQL service to be ready
        run: |
          until mysqladmin ping -h mysql --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Test MySQL Connection
        run: |
          mysql -h mysql -u "${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -e "SHOW DATABASES;"
        shell: bash

      - name: Test with Maven
        run: mvn test
        working-directory: ./backend

  build:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: maven:3.9-eclipse-temurin-17
      env:
        SPRING_PROFILES_ACTIVE: prod
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install MySQL Client
        run: |
          apt-get update && apt-get install -y mysql-client
        shell: bash

      - name: Wait for MySQL service to be ready
        run: |
          until mysqladmin ping -h mysql --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./backend

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: moviemate-jar
          path: backend/target/movie-mate-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Save PEM key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > aws_key.pem
          chmod 400 aws_key.pem

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: moviemate-jar

      - name: Upload artifact to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i aws_key.pem movie-mate-0.0.1-SNAPSHOT.jar ec2-user@16.171.226.91:/home/ec2-user/app.jar
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH and restart app
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key.pem ec2-user@16.171.226.91 << 'EOF'
            pkill -f 'java -jar' || true
            nohup java -jar /home/ec2-user/movie-mate-0.0.1-SNAPSHOT.jar --spring.profiles.active=no-db > output.log 2>&1 &
          EOF