name: Backend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-17
      env:
        SPRING_PROFILES_ACTIVE: ci
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install MySQL Client
        run: |
          apt-get update && apt-get install -y mysql-client
        shell: bash

      - name: Debug Secrets (Check if they exist)
        run: |
          echo "Checking if secrets exist..."
          [[ -z "${{ secrets.MYSQL_USER }}" ]] && echo "❌ MYSQL_USER is missing!" && exit 1
          [[ -z "${{ secrets.MYSQL_PASSWORD }}" ]] && echo "❌ MYSQL_PASSWORD is missing!" && exit 1
          [[ -z "${{ secrets.MYSQL_DATABASE }}" ]] && echo "❌ MYSQL_DATABASE is missing!" && exit 1
          echo "✅ Secrets are available"

          echo "MYSQL_USER=${MYSQL_USER}"
          echo "MYSQL_PASSWORD length=${#MYSQL_PASSWORD}"
          echo "MYSQL_DATABASE=${MYSQL_DATABASE}"
        shell: bash

      - name: Wait for MySQL service to be ready
        run: |
          until mysqladmin ping -h mysql --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Test MySQL Connection
        run: |
          mysql -h mysql -u "${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -e "SHOW DATABASES;"
        shell: bash

      - name: Print MySQL Logs if Failure
        if: failure()
        run: cat /var/log/mysql/error.log || echo "No MySQL logs found"

      - name: Test with Maven
        run: mvn test
        working-directory: ./backend

      - name: Save Source Code as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tested-source
          path: .

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download Tested Code
        uses: actions/download-artifact@v4
        with:
          name: tested-source
          path: .

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./backend

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: ./backend/target/*.jar